{
    'name': 'Hospital Management',
    'version': '1.0.0',
    'category': 'Hospital',
    'author': 'Viktor',
    'sequence': -100,
    'website': 'www.odoo.tech',
    'summary': 'Hospital management system',
    'depends': ['base', 'mail', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'wizard/create_appointment_view.xml',
        'views/menu.xml',
        'views/doctor.xml',
        'views/patient.xml',
        'views/female_patient.xml',
        'views/appointment.xml',
    ],
    'demo': [],
    'application': True,
}
