{
    'name': 'Hospital Management',
    'version': '1.0.0',
    'category': 'Hospital',
    'author': 'Viktor',
    'sequence': -100,
    'website': 'www.odoo.tech',
    'summary': 'Hospital management system',
    'depends': ['web', 'base', 'mail', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'wizard/create_appointment_view.xml',
        'wizard/search_appointment_view.xml',
        'views/menu.xml',
        'views/doctor.xml',
        'views/patient.xml',
        'views/disease_views.xml',
        'views/female_patient.xml',
        'views/appointment.xml',
        'report/patient_details_template.xml',
        'report/patient_card.xml',
        'report/report.xml',
        # 'demo/disease_demo.xml',
        # 'demo/doctor_demo.xml',
    ],
    'demo': [
        'demo/disease_demo.xml',
        'demo/doctor_demo.xml',
        'demo/patient_demo.xml',
    ],
    'application': True,
}
